# Generated by Django 4.2.8 on 2024-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=1000, max_length=50),
        ),
    ]
