# Generated by Django 4.2.8 on 2024-01-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_user_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='tasks.customuser'),
        ),
    ]
