# Generated by Django 4.2.8 on 2024-01-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_alter_customuser_user_id_alter_task_custom_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='custom_user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tasks.customuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default=3, max_length=50),
        ),
    ]
