# Generated by Django 4.2.8 on 2024-01-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_customuser_user_id_alter_task_custom_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.customuser'),
        ),
    ]
