# Generated by Django 4.2.8 on 2024-01-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_user_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='tasks.customuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
