# Generated by Django 4.2.8 on 2024-01-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_custom_user_id_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
