# Generated by Django 4.2.8 on 2024-01-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='custom_user_id',
        ),
    ]
