# Generated by Django 4.2.8 on 2024-01-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_complete_task_created_task_task_id_customuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='task',
        ),
    ]
