# Generated by Django 4.2.8 on 2024-01-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_rename_task_id_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_id',
        ),
    ]
